name: Build, Push and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  frontend:
    uses: ./.github/workflows/frontend-deploy.yml
    with:
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
      VITE_PUBLIC_POSTHOG_HOST: ${{ vars.VITE_PUBLIC_POSTHOG_HOST }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      VITE_PUBLIC_POSTHOG_KEY: ${{ secrets.VITE_PUBLIC_POSTHOG_KEY }}
